"""Frozen V1 provider and retrieval configuration shared across boundaries."""

OPENAI_GENERATION_MODEL = "gpt-5.6-terra"
OPENAI_GENERATION_MODEL_IDENTIFIER_TYPE = "alias"
OPENAI_GENERATION_ENDPOINT = "responses"
OPENAI_REASONING_EFFORT = "low"
OPENAI_MAX_OUTPUT_TOKENS = 2_000
OPENAI_RESPONSE_STORE = False
OPENAI_STRUCTURED_OUTPUTS_STRICT = True
PROVIDER_GRAPH_CALLS_ENABLED = False

OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIMENSION = 1_536
EMBEDDING_ENCODING = "float"

PINECONE_INDEX_NAME = "rfp-agentic-ai-v1"
PINECONE_NAMESPACE = "northstar-v1"
PINECONE_VECTOR_TYPE = "dense"
PINECONE_METRIC = "dotproduct"
PINECONE_CLOUD = "aws"
PINECONE_REGION = "us-east-1"

CHUNK_MAX_CHARS = 1_200
RETRIEVAL_TOP_K = 5
RETRIEVAL_MIN_RELATIVE_SCORE = 0.25
BM25_K1 = 1.5
BM25_B = 0.75
HYBRID_SPARSE_WEIGHT = 0.60
HYBRID_DENSE_WEIGHT = 0.40
